# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: tapclic_test
        ports: ['3306:3306']
        options: >-
          --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql
          tools: composer, php-cs-fixer
      - name: Install dependencies
        run: |
          cd backend
          composer install --no-progress --prefer-dist --optimize-autoloader
      - name: Lint PHP
        run: |
          cd backend
          php-cs-fixer fix --dry-run --diff --verbose
      - name: Run PHPUnit
        run: |
          cd backend
          cp .env.example .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_DATABASE=tapclic_test" >> .env
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=root" >> .env
          ./vendor/bin/phpunit --testdox

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: |
          cd frontend
          npm ci
      - name: Lint
        run: |
          cd frontend
          npm run lint
      - name: Test
        run: |
          cd frontend
          npm run test:unit
      - name: Build
        run: |
          cd frontend
          npm run build
